FROM golang:1.25-alpine AS go-builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /interfaces ./cmd/interfaces

FROM gcr.io/distroless/static-debian12
COPY --from=go-builder /interfaces /interfaces
EXPOSE 8083
ENTRYPOINT ["/interfaces"]
