// Package testdata provides the XML test data generation engine.
// It parses a sample XML, identifies leaf fields with auto-detected types,
// and generates N varied XML documents returned as a ZIP archive.
//
// Generation modes per field:
//   - random     — generate values within type-specific constraints
//   - fixed      — always use the supplied literal value
//   - expression — build a value from a template string; {field.path} inserts
//     another field's generated value, {random} inserts a random value for
//     this field's type settings
//
// Two CSV modes:
//
//  1. Flat CSV — no __doc__ column. Column headers = field paths.
//     One row = one document. Count is taken from row count.
//     Field configs (expression/random) still apply to unmatched paths.
//
//  2. Nested CSV — has a __doc__ column (generated by GenerateCSVTemplate).
//     Rows with the same __doc__ value form one XML document.
//     Repeating elements are expanded per-group. Field configs are ignored;
//     all values come from the CSV.
package testdata

import (
	"archive/zip"
	"bytes"
	"encoding/csv"
	"encoding/xml"
	"fmt"
	"io"
	"math/rand"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// Field types
const (
	TypeString   = "string"
	TypeInteger  = "integer"
	TypeDecimal  = "decimal"
	TypeDate     = "date"
	TypeDatetime = "datetime"
	TypeBoolean  = "boolean"
)

// Generation modes
const (
	ModeRandom     = "random"
	ModeFixed      = "fixed"
	ModeExpression = "expression"
	ModeLookup     = "lookup"
)

// --- Public types ---

// Field is a leaf XML element identified during analysis.
type Field struct {
	Path         string `json:"path"`
	SampleValue  string `json:"sample_value"`
	DetectedType string `json:"detected_type"`
}

// AnalyseResult is returned by Analyse and AnalyseXSD.
type AnalyseResult struct {
	Fields              []Field  `json:"fields"`
	RepeatPoints        []string `json:"repeat_points"`
	SynthesizedTemplate string   `json:"synthesized_template,omitempty"` // set only by AnalyseXSD
}

// CSVTemplateResult is returned by GenerateCSVTemplate.
// CSV is a ready-to-use CSV string with __doc__ column + one sample row per
// cross-product expansion of the repeating elements in the sample XML.
type CSVTemplateResult struct {
	CSV          string   `json:"csv"`
	RepeatPoints []string `json:"repeat_points"`
}

// FieldConfig describes how to generate values for one field.
type FieldConfig struct {
	Path          string   `json:"path"`
	Type          string   `json:"type"`
	Mode          string   `json:"mode"`                     // "random" | "fixed" | "expression" | "lookup"
	Value         string   `json:"value,omitempty"`          // fixed mode
	Expression    string   `json:"expression,omitempty"`     // expression mode template
	Min           float64  `json:"min,omitempty"`            // integer / decimal random
	Max           float64  `json:"max,omitempty"`
	DecimalPlaces int      `json:"decimal_places,omitempty"` // decimal random
	DateStart     string   `json:"date_start,omitempty"`     // date / datetime random
	DateEnd       string   `json:"date_end,omitempty"`
	Prefix        string   `json:"prefix,omitempty"` // string random
	Length        int      `json:"length,omitempty"`
	LookupTableID string   `json:"lookup_table_id,omitempty"` // lookup mode — resolved by handler
	LookupValues  []string `json:"lookup_values,omitempty"`   // lookup mode — populated before Generate is called
}

// GenerateRequest is the payload for Generate.
type GenerateRequest struct {
	Template string        `json:"template"`
	Count    int           `json:"count"`
	Fields   []FieldConfig `json:"fields"`
	CSVData  string        `json:"csv_data,omitempty"` // raw CSV; when set, Count is ignored
}

// --- XML node ---

type xmlNode struct {
	Name     string
	NS       string
	Attrs    []xml.Attr
	NSDecls  []xml.Attr
	Text     string
	Children []*xmlNode
}

// --- Public API ---

// Analyse parses the XML and returns every unique leaf-node path with its
// sample value and auto-detected type, plus any paths that are repeat points
// (elements that appear more than once under the same parent).
func Analyse(content string) (AnalyseResult, error) {
	root, err := parseXML(content)
	if err != nil {
		return AnalyseResult{}, err
	}
	var fields []Field
	seen := make(map[string]bool)
	collectLeaves(root, root.Name, seen, &fields)
	repeatPoints := findRepeatPoints(root, root.Name)
	return AnalyseResult{Fields: fields, RepeatPoints: repeatPoints}, nil
}

// GenerateCSVTemplate creates a CSV template from the sample XML.
// The first column is __doc__ (document number). Remaining columns are leaf
// paths in document order. Repeating elements are cross-product expanded so
// the sample shows one row per combination of repeated instances.
// The user fills in additional rows and returns the CSV for generation.
func GenerateCSVTemplate(content string) (CSVTemplateResult, error) {
	root, err := parseXML(content)
	if err != nil {
		return CSVTemplateResult{}, err
	}
	repeatPoints := findRepeatPoints(root, root.Name)

	// Ordered leaf paths (DFS, first occurrence only)
	var cols []string
	colSeen := make(map[string]bool)
	collectLeafPathsOrdered(root, root.Name, colSeen, &cols)

	// Flatten sample XML into rows via cross-product expansion
	rows := flattenNode(root, root.Name)

	var buf bytes.Buffer
	w := csv.NewWriter(&buf)

	header := make([]string, 0, len(cols)+1)
	header = append(header, "__doc__")
	header = append(header, cols...)
	_ = w.Write(header) //nolint:errcheck

	for _, row := range rows {
		record := make([]string, len(header))
		record[0] = "1"
		for j, col := range cols {
			record[j+1] = row[col]
		}
		_ = w.Write(record) //nolint:errcheck
	}
	w.Flush()

	return CSVTemplateResult{
		CSV:          buf.String(),
		RepeatPoints: repeatPoints,
	}, nil
}

// Generate produces XML documents with field values varied according to the
// supplied FieldConfigs, and returns the documents as a ZIP archive.
//
// If CSVData contains a __doc__ column (nested mode), rows are grouped by
// __doc__ value and each group builds one XML document using repeat-aware
// expansion. FieldConfigs are ignored in this mode.
//
// If CSVData has no __doc__ column (flat mode), each CSV row becomes one
// document; Count is ignored. FieldConfigs still apply to unmatched paths.
//
// If CSVData is empty, Count documents are generated (capped at 1000)
// using FieldConfigs only.
func Generate(req GenerateRequest) ([]byte, error) {
	if strings.TrimSpace(req.CSVData) != "" && hasDocColumn(req.CSVData) {
		return generateFromNestedCSV(req)
	}
	return generateFlat(req)
}

// --- Nested CSV generation ---

func generateFromNestedCSV(req GenerateRequest) ([]byte, error) {
	allRows, err := parseCSVRows(req.CSVData)
	if err != nil {
		return nil, fmt.Errorf("CSV: %w", err)
	}
	groups := groupByDoc(allRows)
	if len(groups) == 0 {
		return nil, fmt.Errorf("CSV: no documents found")
	}

	// Derive repeat points from the template
	tmplRoot, err := parseXML(req.Template)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}
	repeatPoints := findRepeatPoints(tmplRoot, tmplRoot.Name)

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	for i, docRows := range groups {
		root, err := parseXML(req.Template)
		if err != nil {
			return nil, fmt.Errorf("parse template: %w", err)
		}
		built := buildNodeFromRows(root, docRows, root.Name, repeatPoints)
		xmlContent := `<?xml version="1.0" encoding="UTF-8"?>` + "\n" + renderNode(built, 0)
		fw, err := zw.Create(fmt.Sprintf("record_%04d.xml", i+1))
		if err != nil {
			return nil, fmt.Errorf("zip create: %w", err)
		}
		if _, err := fw.Write([]byte(xmlContent)); err != nil {
			return nil, fmt.Errorf("zip write: %w", err)
		}
	}

	if err := zw.Close(); err != nil {
		return nil, fmt.Errorf("zip close: %w", err)
	}
	return buf.Bytes(), nil
}

// buildNodeFromRows recursively rebuilds an XML node using values from rows.
// At repeat points, one child is cloned per consecutive group of rows that
// share the same values for fields "at" that level (i.e. direct leaf fields
// of that repeat point, not fields belonging to deeper repeat points).
func buildNodeFromRows(tmplNode *xmlNode, rows []map[string]string, path string, repeatPoints []string) *xmlNode {
	node := &xmlNode{
		Name:    tmplNode.Name,
		NS:      tmplNode.NS,
		Attrs:   tmplNode.Attrs,
		NSDecls: tmplNode.NSDecls,
	}

	if len(tmplNode.Children) == 0 {
		// Leaf: take value from first row
		if len(rows) > 0 {
			node.Text = rows[0][path]
		}
		return node
	}

	// Group children by tag to detect repeat points and get one template child
	tagOrder, tagMap := groupChildrenByTag(tmplNode)

	for _, tag := range tagOrder {
		children := tagMap[tag]
		childPath := path + "." + tag

		if isRepeatPoint(childPath, repeatPoints) {
			// One cloned child per consecutive group sharing the same level fields
			groups := groupConsecutiveByLevelFields(rows, childPath, repeatPoints)
			for _, group := range groups {
				child := buildNodeFromRows(children[0], group, childPath, repeatPoints)
				node.Children = append(node.Children, child)
			}
		} else {
			// Non-repeating: use first template child; pass all rows through
			child := buildNodeFromRows(children[0], rows, childPath, repeatPoints)
			node.Children = append(node.Children, child)
		}
	}

	return node
}

// groupConsecutiveByLevelFields groups consecutive rows where all
// "level-specific" leaf paths (those under levelPath but not under any deeper
// repeat point) have the same values.
// If no level-specific paths exist, each row becomes its own group.
func groupConsecutiveByLevelFields(rows []map[string]string, levelPath string, repeatPoints []string) [][]map[string]string {
	levelFields := getLevelLeafPaths(rows, levelPath, repeatPoints)

	if len(levelFields) == 0 {
		// No distinguishing fields at this level; each row = one instance
		groups := make([][]map[string]string, len(rows))
		for i, row := range rows {
			groups[i] = []map[string]string{row}
		}
		return groups
	}

	key := func(row map[string]string) string {
		var parts []string
		for _, f := range levelFields {
			parts = append(parts, f+"="+row[f])
		}
		return strings.Join(parts, "|")
	}

	var groups [][]map[string]string
	var current []map[string]string
	var currentKey string

	for _, row := range rows {
		k := key(row)
		if len(current) == 0 || k == currentKey {
			current = append(current, row)
			currentKey = k
		} else {
			groups = append(groups, current)
			current = []map[string]string{row}
			currentKey = k
		}
	}
	if len(current) > 0 {
		groups = append(groups, current)
	}
	return groups
}

// getLevelLeafPaths returns all leaf paths present in rows that:
//   - start with levelPath + "."
//   - are NOT under any deeper repeat point (a repeat point that is itself
//     under levelPath)
func getLevelLeafPaths(rows []map[string]string, levelPath string, repeatPoints []string) []string {
	if len(rows) == 0 {
		return nil
	}
	prefix := levelPath + "."
	seen := make(map[string]bool)
	var result []string
	for _, row := range rows {
		for k := range row {
			if k == "__doc__" || seen[k] {
				continue
			}
			if !strings.HasPrefix(k, prefix) {
				continue
			}
			underDeeper := false
			for _, rp := range repeatPoints {
				if rp == levelPath {
					continue
				}
				// Only consider repeat points that are themselves children of levelPath
				if strings.HasPrefix(rp, prefix) && strings.HasPrefix(k, rp+".") {
					underDeeper = true
					break
				}
			}
			if !underDeeper {
				seen[k] = true
				result = append(result, k)
			}
		}
	}
	return result
}

func isRepeatPoint(path string, repeatPoints []string) bool {
	for _, rp := range repeatPoints {
		if rp == path {
			return true
		}
	}
	return false
}

// GenerateSingle produces one XML document from the request and returns it as a string.
func GenerateSingle(req GenerateRequest) (string, error) {
	req.Count = 1
	return generateDoc(req, nil, 0, rand.New(rand.NewSource(time.Now().UnixNano()))) //nolint:gosec
}

// GenerateBatch produces all documents as a slice of XML strings.
// Used by the "Save to Assets" flow so each document can be stored individually.
func GenerateBatch(req GenerateRequest) ([]string, error) {
	if strings.TrimSpace(req.CSVData) != "" && hasDocColumn(req.CSVData) {
		return nil, fmt.Errorf("batch save is not supported for nested CSV mode; use the ZIP download instead")
	}

	var csvColumns map[string][]string
	csvRows := 0
	if strings.TrimSpace(req.CSVData) != "" {
		var err error
		csvColumns, csvRows, err = parseCSV(req.CSVData)
		if err != nil {
			return nil, fmt.Errorf("CSV: %w", err)
		}
	}

	count := req.Count
	if csvRows > 0 {
		count = csvRows
	}
	if count <= 0 {
		count = 1
	}
	if count > 1000 {
		count = 1000
	}

	rng := rand.New(rand.NewSource(time.Now().UnixNano())) //nolint:gosec
	docs := make([]string, 0, count)

	for i := 0; i < count; i++ {
		csvRow := make(map[string]string)
		for path, vals := range csvColumns {
			if i < len(vals) {
				csvRow[path] = vals[i]
			}
		}
		xml, err := generateDoc(req, csvRow, i, rng)
		if err != nil {
			return nil, err
		}
		docs = append(docs, xml)
	}
	return docs, nil
}

// generateDoc produces one XML document for document index i, seeding computed
// values from csvRow first (may be nil), then applying field configs.
func generateDoc(req GenerateRequest, csvRow map[string]string, i int, rng *rand.Rand) (string, error) {
	root, err := parseXML(req.Template)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	computed := make(map[string]string)
	for path, val := range csvRow {
		computed[path] = val
	}

	// Step 1: random / fixed / lookup fields (CSV takes precedence)
	for _, fc := range req.Fields {
		if fc.Mode == ModeExpression {
			continue
		}
		if _, fromCSV := computed[fc.Path]; fromCSV {
			continue
		}
		if fc.Mode == ModeLookup && len(fc.LookupValues) > 0 {
			computed[fc.Path] = fc.LookupValues[i%len(fc.LookupValues)]
			continue
		}
		computed[fc.Path] = generateValue(fc, rng)
	}

	// Step 2: expression fields
	for _, fc := range req.Fields {
		if fc.Mode != ModeExpression {
			continue
		}
		computed[fc.Path] = resolveExpression(fc.Expression, computed, fc, rng)
	}

	for path, val := range computed {
		segs := strings.Split(path, ".")
		if len(segs) > 1 && segs[0] == root.Name {
			applyValue(root, segs[1:], val)
		}
	}

	return `<?xml version="1.0" encoding="UTF-8"?>` + "\n" + renderNode(root, 0), nil
}

// --- Flat CSV generation (existing behaviour) ---

func generateFlat(req GenerateRequest) ([]byte, error) {
	var csvColumns map[string][]string
	csvRows := 0
	if strings.TrimSpace(req.CSVData) != "" {
		var err error
		csvColumns, csvRows, err = parseCSV(req.CSVData)
		if err != nil {
			return nil, fmt.Errorf("CSV: %w", err)
		}
	}

	count := req.Count
	if csvRows > 0 {
		count = csvRows
	}
	if count <= 0 {
		count = 1
	}
	if count > 1000 {
		count = 1000
	}

	rng := rand.New(rand.NewSource(time.Now().UnixNano())) //nolint:gosec

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	for i := 0; i < count; i++ {
		// Build CSV row map for this index
		csvRow := make(map[string]string)
		for path, vals := range csvColumns {
			if i < len(vals) {
				csvRow[path] = vals[i]
			}
		}

		xmlContent, err := generateDoc(req, csvRow, i, rng)
		if err != nil {
			return nil, err
		}

		fw, err := zw.Create(fmt.Sprintf("record_%04d.xml", i+1))
		if err != nil {
			return nil, fmt.Errorf("zip create: %w", err)
		}
		if _, err := fw.Write([]byte(xmlContent)); err != nil {
			return nil, fmt.Errorf("zip write: %w", err)
		}
	}

	if err := zw.Close(); err != nil {
		return nil, fmt.Errorf("zip close: %w", err)
	}
	return buf.Bytes(), nil
}

// --- CSV parsing ---

// hasDocColumn reports whether the first line of data contains a __doc__ column.
func hasDocColumn(data string) bool {
	line := strings.SplitN(strings.TrimSpace(data), "\n", 2)[0]
	for _, col := range strings.Split(line, ",") {
		if strings.TrimSpace(col) == "__doc__" {
			return true
		}
	}
	return false
}

// parseCSVRows parses CSV into a slice of row maps (header → value).
func parseCSVRows(data string) ([]map[string]string, error) {
	r := csv.NewReader(strings.NewReader(data))
	r.TrimLeadingSpace = true
	records, err := r.ReadAll()
	if err != nil {
		return nil, err
	}
	if len(records) < 2 {
		return nil, fmt.Errorf("must have a header row and at least one data row")
	}
	headers := records[0]
	rows := make([]map[string]string, 0, len(records)-1)
	for _, rec := range records[1:] {
		row := make(map[string]string, len(headers))
		for i, h := range headers {
			h = strings.TrimSpace(h)
			val := ""
			if i < len(rec) {
				val = strings.TrimSpace(rec[i])
			}
			row[h] = val
		}
		rows = append(rows, row)
	}
	return rows, nil
}

// groupByDoc groups rows by __doc__ value, preserving document order.
func groupByDoc(rows []map[string]string) [][]map[string]string {
	var order []string
	groups := make(map[string][]map[string]string)
	for _, row := range rows {
		doc := row["__doc__"]
		if _, exists := groups[doc]; !exists {
			order = append(order, doc)
		}
		groups[doc] = append(groups[doc], row)
	}
	result := make([][]map[string]string, 0, len(order))
	for _, doc := range order {
		result = append(result, groups[doc])
	}
	return result
}

// parseCSV reads flat CSV content (first row = headers = field paths) and returns
// a map of path → []string values (one entry per data row) plus the row count.
func parseCSV(data string) (map[string][]string, int, error) {
	r := csv.NewReader(strings.NewReader(data))
	r.TrimLeadingSpace = true
	records, err := r.ReadAll()
	if err != nil {
		return nil, 0, err
	}
	if len(records) < 2 {
		return nil, 0, fmt.Errorf("must have a header row and at least one data row")
	}
	headers := records[0]
	cols := make(map[string][]string, len(headers))
	for _, h := range headers {
		cols[strings.TrimSpace(h)] = nil
	}
	for _, row := range records[1:] {
		for i, h := range headers {
			h = strings.TrimSpace(h)
			val := ""
			if i < len(row) {
				val = strings.TrimSpace(row[i])
			}
			cols[h] = append(cols[h], val)
		}
	}
	return cols, len(records) - 1, nil
}

// --- Expression resolution ---

var tokenRE = regexp.MustCompile(`\{([^}]+)\}`)

func resolveExpression(expr string, computed map[string]string, fc FieldConfig, rng *rand.Rand) string {
	return tokenRE.ReplaceAllStringFunc(expr, func(tok string) string {
		key := tok[1 : len(tok)-1]
		if key == "random" {
			rfc := fc
			rfc.Mode = ModeRandom
			return generateValue(rfc, rng)
		}
		if val, ok := computed[key]; ok {
			return val
		}
		return tok
	})
}

// --- XML parsing ---

func parseXML(content string) (*xmlNode, error) {
	dec := xml.NewDecoder(strings.NewReader(content))
	for {
		tok, err := dec.Token()
		if err == io.EOF {
			return nil, fmt.Errorf("empty XML document")
		}
		if err != nil {
			return nil, fmt.Errorf("XML parse: %w", err)
		}
		if se, ok := tok.(xml.StartElement); ok {
			return buildNode(dec, se)
		}
	}
}

func buildNode(dec *xml.Decoder, se xml.StartElement) (*xmlNode, error) {
	node := &xmlNode{Name: se.Name.Local, NS: se.Name.Space}
	for _, a := range se.Attr {
		if a.Name.Space == "xmlns" || (a.Name.Space == "" && a.Name.Local == "xmlns") {
			node.NSDecls = append(node.NSDecls, a)
		} else {
			node.Attrs = append(node.Attrs, a)
		}
	}
	for {
		tok, err := dec.Token()
		if err != nil {
			return nil, err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			child, err := buildNode(dec, t)
			if err != nil {
				return nil, err
			}
			node.Children = append(node.Children, child)
		case xml.EndElement:
			return node, nil
		case xml.CharData:
			if s := strings.TrimSpace(string(t)); s != "" {
				node.Text = s
			}
		}
	}
}

// --- Repeat point detection ---

// findRepeatPoints returns paths where an element appears more than once under
// the same parent in the given XML tree. Only the first occurrence of each
// child tag is recursed into (to avoid duplicate paths).
func findRepeatPoints(node *xmlNode, path string) []string {
	var points []string
	tagCount := make(map[string]int)
	for _, child := range node.Children {
		tagCount[child.Name]++
	}
	for tag, count := range tagCount {
		if count > 1 {
			points = append(points, path+"."+tag)
		}
	}
	// Recurse into the first instance of each child tag
	visited := make(map[string]bool)
	for _, child := range node.Children {
		childPath := path + "." + child.Name
		if !visited[childPath] {
			visited[childPath] = true
			points = append(points, findRepeatPoints(child, childPath)...)
		}
	}
	return points
}

// --- Field analysis ---

func collectLeaves(node *xmlNode, path string, seen map[string]bool, out *[]Field) {
	if len(node.Children) == 0 {
		if !seen[path] {
			seen[path] = true
			*out = append(*out, Field{
				Path:         path,
				SampleValue:  node.Text,
				DetectedType: detectType(node.Text),
			})
		}
		return
	}
	for _, child := range node.Children {
		collectLeaves(child, path+"."+child.Name, seen, out)
	}
}

// collectLeafPathsOrdered collects unique leaf paths in DFS order, recursing
// into only the first occurrence of each child tag (to avoid duplicate columns).
func collectLeafPathsOrdered(node *xmlNode, path string, seen map[string]bool, out *[]string) {
	if len(node.Children) == 0 {
		if !seen[path] {
			seen[path] = true
			*out = append(*out, path)
		}
		return
	}
	visited := make(map[string]bool)
	for _, child := range node.Children {
		if !visited[child.Name] {
			visited[child.Name] = true
			collectLeafPathsOrdered(child, path+"."+child.Name, seen, out)
		}
	}
}

var (
	reInteger  = regexp.MustCompile(`^-?\d+$`)
	reDecimal  = regexp.MustCompile(`^-?\d+\.\d+$`)
	reDate     = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`)
	reDatetime = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}`)
)

func detectType(val string) string {
	v := strings.TrimSpace(val)
	if v == "" {
		return TypeString
	}
	lower := strings.ToLower(v)
	if lower == "true" || lower == "false" || lower == "yes" || lower == "no" {
		return TypeBoolean
	}
	if reDatetime.MatchString(v) {
		return TypeDatetime
	}
	if reDate.MatchString(v) {
		return TypeDate
	}
	if reDecimal.MatchString(v) {
		return TypeDecimal
	}
	if reInteger.MatchString(v) {
		return TypeInteger
	}
	return TypeString
}

// --- CSV template flatten ---

// groupChildrenByTag returns children grouped by tag name, preserving the
// first-seen order of tags.
func groupChildrenByTag(node *xmlNode) ([]string, map[string][]*xmlNode) {
	var tagOrder []string
	tagMap := make(map[string][]*xmlNode)
	for _, child := range node.Children {
		if _, exists := tagMap[child.Name]; !exists {
			tagOrder = append(tagOrder, child.Name)
		}
		tagMap[child.Name] = append(tagMap[child.Name], child)
	}
	return tagOrder, tagMap
}

// flattenNode expands a node into a slice of row maps (leaf path → value) by
// taking the cross-product of all child tag groups. Repeated child tags are
// concatenated (each instance contributes its own rows).
func flattenNode(node *xmlNode, path string) []map[string]string {
	if len(node.Children) == 0 {
		return []map[string]string{{path: node.Text}}
	}

	tagOrder, tagMap := groupChildrenByTag(node)

	result := []map[string]string{{}} // start: one empty row
	for _, tag := range tagOrder {
		childPath := path + "." + tag
		var tagRows []map[string]string
		for _, child := range tagMap[tag] {
			tagRows = append(tagRows, flattenNode(child, childPath)...)
		}
		result = crossProduct(result, tagRows)
	}
	return result
}

func crossProduct(a, b []map[string]string) []map[string]string {
	if len(a) == 0 {
		return b
	}
	if len(b) == 0 {
		return a
	}
	result := make([]map[string]string, 0, len(a)*len(b))
	for _, ra := range a {
		for _, rb := range b {
			merged := make(map[string]string, len(ra)+len(rb))
			for k, v := range ra {
				merged[k] = v
			}
			for k, v := range rb {
				merged[k] = v
			}
			result = append(result, merged)
		}
	}
	return result
}

// --- Value application (flat mode) ---

func applyValue(node *xmlNode, segs []string, val string) {
	if len(segs) == 0 {
		node.Text = val
		return
	}
	for _, child := range node.Children {
		if child.Name == segs[0] {
			applyValue(child, segs[1:], val)
		}
	}
}

// --- Value generation ---

const charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

func generateValue(fc FieldConfig, rng *rand.Rand) string {
	if fc.Mode == ModeFixed {
		return fc.Value
	}
	switch fc.Type {
	case TypeInteger:
		lo, hi := int64(fc.Min), int64(fc.Max)
		if hi <= lo {
			lo, hi = 1000, 9999
		}
		return strconv.FormatInt(lo+rng.Int63n(hi-lo+1), 10)

	case TypeDecimal:
		lo, hi := fc.Min, fc.Max
		if hi <= lo {
			lo, hi = 1.0, 100.0
		}
		dp := fc.DecimalPlaces
		if dp <= 0 {
			dp = 2
		}
		return strconv.FormatFloat(lo+rng.Float64()*(hi-lo), 'f', dp, 64)

	case TypeDate:
		return randomDate(rng, fc.DateStart, fc.DateEnd, "2006-01-02")

	case TypeDatetime:
		return randomDate(rng, fc.DateStart, fc.DateEnd, "2006-01-02T15:04:05")

	case TypeBoolean:
		if rng.Intn(2) == 0 {
			return "true"
		}
		return "false"

	default: // string
		n := fc.Length
		if n <= 0 {
			n = 8
		}
		b := make([]byte, n)
		for i := range b {
			b[i] = charset[rng.Intn(len(charset))]
		}
		return fc.Prefix + string(b)
	}
}

func randomDate(rng *rand.Rand, start, end, format string) string {
	const layout = "2006-01-02"
	now := time.Now()
	s := now.AddDate(-1, 0, 0)
	e := now
	if t, err := time.Parse(layout, start); err == nil {
		s = t
	}
	if t, err := time.Parse(layout, end); err == nil {
		e = t
	}
	if e.Before(s) {
		s, e = e, s
	}
	diff := e.Sub(s)
	if diff <= 0 {
		return s.Format(format)
	}
	return s.Add(time.Duration(rng.Int63n(int64(diff)))).Format(format)
}

// --- XML serialisation ---

func renderNode(node *xmlNode, depth int) string {
	indent := strings.Repeat("  ", depth)
	var sb strings.Builder
	sb.WriteString(indent + "<" + node.Name)
	for _, a := range node.NSDecls {
		if a.Name.Space == "xmlns" {
			sb.WriteString(fmt.Sprintf(` xmlns:%s="%s"`, a.Name.Local, a.Value))
		} else {
			sb.WriteString(fmt.Sprintf(` xmlns="%s"`, a.Value))
		}
	}
	for _, a := range node.Attrs {
		name := a.Name.Local
		if a.Name.Space != "" {
			name = a.Name.Space + ":" + name
		}
		sb.WriteString(fmt.Sprintf(` %s="%s"`, name, escAttr(a.Value)))
	}
	if node.Text == "" && len(node.Children) == 0 {
		sb.WriteString("/>\n")
		return sb.String()
	}
	sb.WriteString(">")
	if len(node.Children) > 0 {
		sb.WriteString("\n")
		for _, c := range node.Children {
			sb.WriteString(renderNode(c, depth+1))
		}
		sb.WriteString(indent + "</" + node.Name + ">\n")
	} else {
		sb.WriteString(escText(node.Text) + "</" + node.Name + ">\n")
	}
	return sb.String()
}

func escText(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}

func escAttr(s string) string {
	s = escText(s)
	s = strings.ReplaceAll(s, `"`, "&quot;")
	return s
}
