ALTER TABLE test_cases ADD COLUMN IF NOT EXISTS type        TEXT NOT NULL DEFAULT 'http';
ALTER TABLE test_cases ADD COLUMN IF NOT EXISTS sftp_source TEXT NOT NULL DEFAULT '';
ALTER TABLE test_cases ADD COLUMN IF NOT EXISTS sftp_target TEXT NOT NULL DEFAULT '';
